### ISSUE TITLE
Release Year

### ISSUE THREAD

**Issue by luxuryballs** [aaronpenne/somafm_charts#1]
Dear  aaronpenne,

Thank you for your repo.

Just to let you know, the python script doesnt export the year that the media was released.

Please could you give me an update to if the script can export year of release in the scraper?

Thank you.

**Comment by aaronpenne** [comment]
Hello, I won't be adding any features to this as it was an old project no longer in use. Feel free to add the required feature and submit a pull request. Thanks!
